
language: node_js
node_js:
- "stable"
cache:
  directories:
    - "node_modules"

env:
  global:
    - DATABASE_URL : postgres://travis@localhost:5432/travis
    - PRIVATE_KEY : secr3t!
before_script:
  - psql -c 'create database travis;' -U postgres
  - 
script: npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - npm run coverage

services:
- postgres