const sql = {};

const seedAdmin = 'INSERT INTO users(firstname, lastname, username, email, password, isActive, isAdmin) VALUES ($1, $2, $3, $4, $5, $6, $7) ON CONFLICT (email) DO NOTHING';
const registerUser = 'INSERT INTO users(firstname, lastname, username, email, password) VALUES ($1, $2, $3, $4, $5) RETURNING * ';
const retrieveAllUsers = 'SELECT * FROM users';
const loginUser = 'SELECT * FROM users WHERE email = $1';
const retrieveSpecificUser = 'SELECT * FROM users WHERE email = $1';
const retrieveSpecificUserById = 'SELECT * FROM users WHERE id = $1';
const deleteSpecificUser = 'DELETE FROM users WHERE id = $1';
const sendEmail = 'INSERT INTO sentEmails(subject, message, senderEmail, receiverEmail, status) VALUES ($1, $2, $3, $4, $5) RETURNING *';
const draftEmail = 'INSERT INTO draftEmails(subject, message, senderEmail, receiverEmail, status) VALUES ($1, $2, $3, $4, $5) RETURNING *';
const delivered = 'INSERT INTO receivedEmails(subject, message, senderEmail, receiverEmail, status) VALUES ($1, $2, $3, $4, $5)';
const emailRead = 'UPDATE receivedEmails SET status = $1 WHERE id = $2 RETURNING *';
const retrieveAllEmails = 'SELECT * FROM receivedEmails';
const retrieveSpecificReceivedEmail = 'SELECT * FROM receivedEmails WHERE id = $1 AND receiverEmail = $2';
const retrieveSpecificSentEmail = 'SELECT * FROM sentEmails WHERE id = $1 AND senderEmail = $2';
const retrieveSpecificDraftEmail = 'SELECT * FROM draftEmails WHERE id = $1 AND senderEmail = $2';
const deleteSpecificEmail = 'DELETE FROM receivedEmails WHERE id = $1';
const deleteSpecificSentEmail = 'DELETE FROM sentEmails WHERE id = $1';
const deleteSpecificDraftEmail = 'DELETE FROM draftEmails WHERE id = $1';
const retrieveSentEmails = 'SELECT * FROM sentEmails WHERE senderEmail = $1';
const retrieveReadEmails = 'SELECT * FROM receivedEmails WHERE status = $1 AND receiverEmail = $2';
const retrieveUnreadEmails = 'SELECT * FROM receivedEmails WHERE status = $1 AND receiverEmail = $2';
const retrieveDraftEmails = 'SELECT * FROM draftEmails WHERE status = $1 AND senderEmail = $2';
const findUserEmail = 'SELECT * FROM users WHERE email = $1';
const findUsername = 'SELECT * FROM users WHERE username = $1';
const retrieveAdmin = 'SELECT * FROM users WHERE email = $1 AND isAdmin = $2';
const retrieveUserSpecificReceivedEmail = 'SELECT * FROM receivedEmails WHERE id = $1 AND receiverEmail = $2';
const adminRetrieveUserSpecificReceivedEmail = 'SELECT * FROM receivedEmails WHERE id = $1';
const retrieveUserSpecificSentEmail = 'SELECT * FROM sentEmails WHERE id = $1 AND senderEmail = $2';
const adminRetrieveUserSpecificSentEmail = 'SELECT * FROM sentEmails WHERE id = $1';
const retrieveUserSpecificDraftEmail = 'SELECT * FROM draftEmails WHERE id = $1 AND senderEmail = $2';
const adminRetrieveUserSpecificDraftEmail = 'SELECT * FROM draftEmails WHERE id = $1';
const adminGetSentEmails = 'SELECT * FROM sentEmails';
const adminGetReadEmails = 'SELECT * FROM receivedEmails WHERE status = $1';
const adminGetUnreadEmails = 'SELECT * FROM receivedEmails WHERE status = $1';
const adminGetDraftEmails = 'SELECT * FROM draftEmails WHERE status = $1';
const createGroup = 'INSERT INTO groups(name, purpose, owner) VALUES($1, $2, $3) RETURNING *';
const retrieveAllGroups = 'SELECT * FROM groups';
const retrieveSpecificGroup = 'SELECT * FROM groups WHERE id = $1';
const updateSpecificGroup = 'UPDATE groups SET name = $1 WHERE id = $2 RETURNING *';
const deleteSpecificGroup = 'DELETE FROM groups WHERE id = $1';
const registerGroupMember = 'INSERT INTO groupMembers(username, email, groupId) VALUES ($1, $2, $3) RETURNING * ';
const retrieveSpecificGroupOwner = 'SELECT * FROM groups WHERE id = $1 AND owner = $2';
const retrieveSpecificGroupMember = 'SELECT * FROM groupMembers WHERE email = $1 AND groupId = $2';
const retrieveSpecificGroupMemberById = 'SELECT * FROM groupMembers WHERE id = $1 AND groupId = $2';
const deleteSpecificGroupMember = 'DELETE FROM groupMembers WHERE id = $1 AND groupId = $2';
const sendGroupEmail = 'INSERT INTO groupMessages(message, groupId) VALUES ($1, $2) RETURNING *';
const deleteSpecificUserPassword = 'UPDATE users SET password = null WHERE email = $1 ';
const retrieveUserGroups = 'SELECT * FROM groups WHERE owner = $1';
const retrieveUserGroup = 'SELECT * FROM groups WHERE id = $1 AND owner = $2';
const retrieveSpecificGroupMembers = 'SELECT * FROM groupMembers WHERE groupId = $1';
const retrieveSpecificGroupEmails = 'SELECT * FROM groupMessages WHERE groupId = $1';
const retrievePassResetUsers = 'SELECT * FROM users WHERE password isNull';
const retrieveMemberByUsername = 'SELECT * FROM groupMembers WHERE username = $1 AND groupId = $2';
const retrieveMemberByEmail = 'SELECT * FROM groupMembers WHERE email = $1 AND groupId = $2';
const findGroup = 'SELECT * FROM groups WHERE name = $1 AND owner = $2';
const retrieveSpecificUserEmails = 'SELECT * FROM receivedEmails WHERE receiverEmail = $1';
const passResetCheck = 'SELECT * FROM users WHERE email = $1 AND password isNull';
const retrieveMemberEmails = 'SELECT * FROM groupMessages WHERE groupId = $1';

/**
 * Add the Queries into the SQL Object
 */
sql.seedAdmin = seedAdmin;
sql.registerUser = registerUser;
sql.loginUser = loginUser;
sql.retrieveAllUsers = retrieveAllUsers;
sql.retrieveSpecificUser = retrieveSpecificUser;
sql.retrieveSpecificUserById = retrieveSpecificUserById;
sql.deleteSpecificUser = deleteSpecificUser;
sql.sendEmail = sendEmail;
sql.delivered = delivered;
sql.emailRead = emailRead;
sql.draftEmail = draftEmail;
sql.retrieveAllEmails = retrieveAllEmails;
sql.retrieveSpecificReceivedEmail = retrieveSpecificReceivedEmail;
sql.retrieveSpecificSentEmail = retrieveSpecificSentEmail;
sql.retrieveSpecificDraftEmail = retrieveSpecificDraftEmail;
sql.deleteSpecificEmail = deleteSpecificEmail;
sql.deleteSpecificSentEmail = deleteSpecificSentEmail;
sql.deleteSpecificDraftEmail = deleteSpecificDraftEmail;
sql.retrieveSentEmails = retrieveSentEmails;
sql.retrieveReadEmails = retrieveReadEmails;
sql.retrieveUnreadEmails = retrieveUnreadEmails;
sql.retrieveDraftEmails = retrieveDraftEmails;
sql.findUserEmail = findUserEmail;
sql.findUsername = findUsername;
sql.retrieveAdmin = retrieveAdmin;
sql.retrieveUserSpecificReceivedEmail = retrieveUserSpecificReceivedEmail;
sql.adminRetrieveUserSpecificReceivedEmail = adminRetrieveUserSpecificReceivedEmail;
sql.retrieveUserSpecificSentEmail = retrieveUserSpecificSentEmail;
sql.adminRetrieveUserSpecificSentEmail = adminRetrieveUserSpecificSentEmail;
sql.retrieveUserSpecificDraftEmail = retrieveUserSpecificDraftEmail;
sql.adminRetrieveUserSpecificDraftEmail = adminRetrieveUserSpecificDraftEmail;
sql.adminGetSentEmails = adminGetSentEmails;
sql.adminGetReadEmails = adminGetReadEmails;
sql.adminGetUnreadEmails = adminGetUnreadEmails;
sql.adminGetDraftEmails = adminGetDraftEmails;
sql.createGroup = createGroup;
sql.retrieveAllGroups = retrieveAllGroups;
sql.retrieveSpecificGroup = retrieveSpecificGroup;
sql.updateSpecificGroup = updateSpecificGroup;
sql.deleteSpecificGroup = deleteSpecificGroup;
sql.registerGroupMember = registerGroupMember;
sql.retrieveSpecificGroupOwner = retrieveSpecificGroupOwner;
sql.retrieveSpecificGroupMember = retrieveSpecificGroupMember;
sql.retrieveSpecificGroupMemberById = retrieveSpecificGroupMemberById;
sql.deleteSpecificGroupMember = deleteSpecificGroupMember;
sql.sendGroupEmail = sendGroupEmail;
sql.deleteSpecificUserPassword = deleteSpecificUserPassword;
sql.retrieveUserGroups = retrieveUserGroups;
sql.retrieveUserGroup = retrieveUserGroup;
sql.retrieveSpecificGroupMembers = retrieveSpecificGroupMembers;
sql.retrieveSpecificGroupEmails = retrieveSpecificGroupEmails;
sql.retrieveMemberEmails = retrieveMemberEmails;
sql.retrievePassResetUsers = retrievePassResetUsers;
sql.retrieveMemberByUsername = retrieveMemberByUsername;
sql.retrieveMemberByEmail = retrieveMemberByEmail;
sql.findGroup = findGroup;
sql.retrieveSpecificUserEmails = retrieveSpecificUserEmails;
sql.passResetCheck = passResetCheck;

export default sql;
